class AppSecreate {
  static const supsrsbaseUrl="https://cbuedqrvzeemiiakdksy.supabase.co";
  static const supsrsbaseAnonKEy="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidWVkcXJ2emVlbWlpYWtka3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQxOTU4MDYsImV4cCI6MjAyOTc3MTgwNn0.2S30wuq0jlHYdiHo-y9wmGDQKggwp9fhmLJ4YTvXVyA";
}